In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [47]:
df = pd.read_csv('final_data_for_vehicle_forecasting.csv')

In [48]:
df.head()

,Halb,engine_type,map_model,Vehicle_Type,Month,total_demand
0,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,01/04/2023,0
1,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,01/05/2023,0
2,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,01/06/2023,0
3,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,01/07/2023,0
4,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,01/08/2023,0

In [49]:
df.shape

(49680, 6)

In [50]:
df.columns

Index(['Halb', 'engine_type', 'map_model', 'Vehicle_Type', 'Month',
       'total_demand'],
      dtype='str')

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49680 entries, 0 to 49679
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Halb          49680 non-null  str
 1   engine_type   49680 non-null  str
 2   map_model     49680 non-null  str
 3   Vehicle_Type  49680 non-null  str
 4   Month         49680 non-null  str
 5   total_demand  49680 non-null  int64
dtypes: int64(1), str(5)
memory usage: 2.3 MB

In [52]:
#Checking Missing Values
df.isnull().sum()

Halb            0
engine_type     0
map_model       0
Vehicle_Type    0
Month           0
total_demand    0
dtype: int64

In [53]:
df.duplicated().sum()

np.int64(0)

In [54]:
df = df.drop_duplicates()

In [55]:
df.describe()

       total_demand
count  49680.000000
mean       3.211131
std       17.137720
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max      677.000000

In [56]:
df['Halb'].unique()

<StringArray>
[  '80206319',   '80251918',   '80401979',   '80600311',   '80601107',
   '80601231',   '80601588',   '80601589',   '80601726',   '80602265',
 ...
 'FERT NA202', 'FERT NA203',   'FERT NA4',   'FERT NA5', 'I6 code na',
 'In Process',     'No BOM',     'bom na',    'code na',   'code na1']
Length: 1772, dtype: str

In [57]:
print(df.columns.tolist())

['Halb', 'engine_type', 'map_model', 'Vehicle_Type', 'Month', 'total_demand']

In [58]:
df['engine_type'].unique()

<StringArray>
[   'E483_BS3_DSL',    'E694_BS4_DSL',    'MDE5_EU3_DSL',    'E683_BS2_DSL',
 'Cummins_EU3_DSL',    'E683_BS3_DSL',    'MDE5_EU4_DSL',    'MDE5_EU5_DSL',
     'MDE5_E5_DSL',    'MDE8_EU3_DSL',    'MDE8_EU4_DSL',    'MDE5 BS4_DSL',
    'E494_EU3_DSL',    'E494_BS3_DSL',    'E483_BS4_DSL',    'E483_EU3_DSL',
    'E494_EU4_DSL',    'E494_EU5_DSL',    'E474_BS4_DSL',    'E474_EU2_DSL',
    'E483_BS1_DSL',    'E483_EU4_DSL',    'E494_BS4_DSL',     'E494_BS3_BD',
     'E494_EU4_BD',    'E366_BS6_DSL',    'E483_BS6_CNG',    'Electric Veh',
    'MDE5_BS6_DSL',    'E694_BS6_CNG',    'MDE8_BS6_DSL',    'E474_BS6_DSL',
    'MDE8_BS6_LNG',    'E494_BS6_DSL',    'E494_BS6_CNG',    'E449_BS6_CNG',
        'BS4-E474',    'MDE8_EU5_DSL',     'E474_E5_DSL',    'E483_EU5_DSL',
    'E449_BS6_DSL',    'E694_BS3_DSL',    'MDE8_BS3_DSL',      'MDE8_Euro5',
              '??',              'EV',        'LNG- BS6',  'MDEP5-LNG- BS6',
             'LNG']
Length: 49, dtype: str

In [59]:
df['map_model'].unique()

<StringArray>
[ '10.60 P/stg with MRF tyres',           '10.60-Cowl, P/stg',
 '10.60G P/stg with MRF tyres',         '10.90-Modular-P/stg',
                  '20.15 cowl',                   '20.15-LPO',
            'Pro 6016-PREMIUM',                 'Pro6018 LHD',
        'Pro 6018 LHD-Premium',                   '20.15 LHD',
 ...
                     'Pro6018',                    'Pro 2116',
                    'Pro 2065',                  'Pro2110XPT',
                    'Skyline ',            'Pro 2110XP-P/stg',
                  '12M EV Bus',                          '??',
            'Pro2116T-PREMIUM',                'Pro 6035XPT ']
Length: 330, dtype: str

In [60]:
df['Vehicle_Type'].unique()

<StringArray>
['Bus', 'LMD', 'HD']
Length: 3, dtype: str

In [61]:
df['Month'].unique()

<StringArray>
['01/04/2023', '01/05/2023', '01/06/2023', '01/07/2023', '01/08/2023',
 '01/09/2023', '01/10/2023', '01/11/2023', '01/12/2023', '01/01/2024',
 '01/02/2024', '01/03/2024', '01/04/2024', '01/05/2024', '01/06/2024',
 '01/07/2024', '01/08/2024', '01/09/2024', '01/10/2024', '01/11/2024',
 '01/12/2024', '01/01/2025', '01/02/2025', '01/03/2025']
Length: 24, dtype: str

In [62]:
df['total_demand'].unique()

array([  0,  10,  16,  15,   5,  20,  40,   7,  33,  25,  35,  46,   4,
         2,   6,   3,  50,  11,  12,   1,   8,   9,  13,  30,  14,  49,
        18,  17,  22,  36,  28,  34,  32,  24,  26,  44,  29,  31,  21,
        19,  38,  23,  27,  60,  45,  41,  51,  55,  39,  54,  58,  85,
        48,  70,  65,  42,  53,  72, 174,  79,  75, 130, 200, 182, 100,
        57,  47,  43,  52,  80, 237,  95, 175,  61, 150,  90, 153,  62,
       180, 140,  97, 185, 230, 260, 138, 105, 125,  88,  69, 126, 236,
       172,  37, 114, 231, 120, 135,  77, 110, 106, 441,  71, 677, 300,
       196,  66,  64,  63,  76,  59, 500, 322, 224, 217, 378, 525, 400,
       170, 284, 590, 425, 239, 560, 176, 235, 325, 430, 324, 280, 297,
       385, 116,  73, 101,  93, 183, 103, 118,  92,  87, 173, 134,  94,
        91, 137,  86, 121,  81, 290,  74, 145,  56, 215, 181, 160,  84,
       210, 141, 169, 255, 199, 139,  98, 115, 112,  78,  83, 117, 207,
       225, 177, 122,  67, 149, 131, 148, 143, 128, 108, 136, 220, 186,
       195, 129,  96, 171, 163,  68, 119, 146, 156, 144, 132, 376, 242,
       240, 155, 307, 429, 158, 203, 104, 194, 123, 107, 127, 159,  99,
       232, 229, 250, 211, 102, 109, 111, 367, 238, 165, 178, 337, 234,
       275, 315, 314, 133, 161,  89, 113, 147, 371, 285])

In [63]:
df['Month'].head(10)

0    01/04/2023
1    01/05/2023
2    01/06/2023
3    01/07/2023
4    01/08/2023
5    01/09/2023
6    01/10/2023
7    01/11/2023
8    01/12/2023
9    01/01/2024
Name: Month, dtype: str

In [64]:
df['Month'] = pd.to_datetime(df['Month'])

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49680 entries, 0 to 49679
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Halb          49680 non-null  str
 1   engine_type   49680 non-null  str
 2   map_model     49680 non-null  str
 3   Vehicle_Type  49680 non-null  str
 4   Month         49680 non-null  datetime64[us]
 5   total_demand  49680 non-null  int64
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 2.3 MB

In [66]:
df = df.sort_values('Month')

In [67]:
df[['Month','total_demand']].head()

           Month  total_demand
0     2023-01-04             0
3720  2023-01-04             0
29040 2023-01-04             0
29016 2023-01-04             0
28992 2023-01-04             0

In [68]:
print("Start Date:", df['Month'].min())
print("End Date:", df['Month'].max())

Start Date: 2023-01-04 00:00:00
End Date: 2025-01-03 00:00:00

In [69]:
df['Month'].nunique()

24

In [70]:
df.to_csv('cleaned_vehicle_data.csv', index=False)

In [71]:
#Creating Overall Monthly Demand Series
monthly_demand = (
    df.groupby('Month')['total_demand']
      .sum()
      .reset_index()
)
monthly_demand.head()

       Month  total_demand
0 2023-01-04          6558
1 2023-01-05          8335
2 2023-01-06          5517
3 2023-01-07          6248
4 2023-01-08          4970

In [72]:
monthly_demand = monthly_demand.sort_values('Month')

In [73]:
print(monthly_demand.index)

RangeIndex(start=0, stop=24, step=1)

In [74]:
df[['Month']].head(10)

           Month
0     2023-01-04
3720  2023-01-04
29040 2023-01-04
29016 2023-01-04
28992 2023-01-04
28968 2023-01-04
28944 2023-01-04
28920 2023-01-04
3744  2023-01-04
28896 2023-01-04

In [75]:
print(df['Month'].min())
print(df['Month'].max())

2023-01-04 00:00:00
2025-01-03 00:00:00

In [77]:
df_raw = pd.read_csv("final_data_for_vehicle_forecasting.csv")
df_raw['Month'].head(10)

0    01/04/2023
1    01/05/2023
2    01/06/2023
3    01/07/2023
4    01/08/2023
5    01/09/2023
6    01/10/2023
7    01/11/2023
8    01/12/2023
9    01/01/2024
Name: Month, dtype: str

In [78]:
df['Month'] = pd.to_datetime(
    df['Month'],
    format='%d/%m/%Y'
)

In [79]:
print(df['Month'].min())
print(df['Month'].max())

2023-01-04 00:00:00
2025-01-03 00:00:00

In [80]:
df = pd.read_csv("final_data_for_vehicle_forecasting.csv")

df['Month'] = pd.to_datetime(
    df['Month'],
    format='%d/%m/%Y'
)

In [81]:
df[['Month']].head(10)

       Month
0 2023-04-01
1 2023-05-01
2 2023-06-01
3 2023-07-01
4 2023-08-01
5 2023-09-01
6 2023-10-01
7 2023-11-01
8 2023-12-01
9 2024-01-01

In [82]:
print(df['Month'].min())
print(df['Month'].max())

2023-04-01 00:00:00
2025-03-01 00:00:00

In [85]:
monthly_demand = (
    df.groupby('Month')['total_demand']
      .sum()
      .reset_index()
)

monthly_demand = monthly_demand.sort_values('Month')

In [86]:
monthly_demand = monthly_demand.set_index('Month')

In [87]:
print(monthly_demand.index.min())
print(monthly_demand.index.max())

print(len(monthly_demand))

2023-04-01 00:00:00
2025-03-01 00:00:00
24

In [88]:
train = monthly_demand.loc[:'2024-12-01']

In [89]:
test = monthly_demand.loc['2025-01-01':'2025-03-01']

In [90]:
print(train.shape)
print(test.shape)

(21, 1)
(3, 1)

In [92]:
train.shape
test.shape

(3, 1)

In [96]:
monthly_demand = (
    df.groupby('Month')['total_demand']
      .sum()
      .reset_index()
)

monthly_demand = monthly_demand.sort_values('Month')
monthly_demand = monthly_demand.set_index('Month')

train = monthly_demand.loc[:'2024-12-01']
test = monthly_demand.loc['2025-01-01':'2025-03-01']

In [97]:
print(train.shape)
print(test.shape)

(21, 1)
(3, 1)

In [102]:
import pandas as pd
import numpy as np

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    mean_absolute_percentage_error
)

from statsmodels.tsa.holtwinters import (
    SimpleExpSmoothing,
    Holt,
    ExponentialSmoothing
)

from statsmodels.tsa.arima.model import ARIMA

from statsmodels.tsa.statespace.sarimax import SARIMAX

import warnings
warnings.filterwarnings("ignore")

In [103]:
df = pd.read_csv("final_data_for_vehicle_forecasting.csv")

df['Month'] = pd.to_datetime(df['Month'])

df.head()

,Halb,engine_type,map_model,Vehicle_Type,Month,total_demand
0,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,2023-01-04,0
1,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,2023-01-05,0
2,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,2023-01-06,0
3,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,2023-01-07,0
4,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,2023-01-08,0

In [104]:
TRAIN_END = pd.Timestamp("2024-12-01")

TEST_START = pd.Timestamp("2025-01-01")

TEST_END = pd.Timestamp("2025-03-01")

In [105]:
#Evaluation Function
def evaluate_forecast(actual, forecast):

    mae = mean_absolute_error(actual, forecast)

    rmse = np.sqrt(
        mean_squared_error(actual, forecast)
    )

    mape = (
        mean_absolute_percentage_error(
            actual,
            forecast
        ) * 100
    )

    accuracy = 100 - mape

    return mae, rmse, mape, accuracy

In [106]:
results = []

In [107]:
#Main Forecasting Loop
for halb in df['Halb'].unique():

    df_h = df[df['Halb'] == halb]

    for engine in df_h['engine_type'].unique():

        df_e = df_h[
            df_h['engine_type'] == engine
        ]

        for model in df_e['map_model'].unique():

            df_m = df_e[
                df_e['map_model'] == model
            ]

            for vehicle in df_m['Vehicle_Type'].unique():

                df_v = df_m[
                    df_m['Vehicle_Type'] == vehicle
                ]

In [108]:
#Monthly Series
agg = (
    df_v.groupby('Month')['total_demand']
        .sum()
        .sort_index()
)

In [113]:
#Train test split
train = agg[
    agg.index <= TRAIN_END
]

test = agg[
    (agg.index >= TEST_START)
    &
    (agg.index <= TEST_END)
]

In [111]:
print(len(train))
print(len(test))

21
3

In [114]:
#ML Models
try:

    forecast = [
        train.tail(3).mean()
    ] * 3

    mae, rmse, mape, acc = (
        evaluate_forecast(
            test,
            forecast
        )
    )

    results.append([
        halb,
        engine,
        model,
        vehicle,
        "Moving Average",
        mae,
        rmse,
        mape,
        acc
    ])

except:
    pass

In [115]:
try:

    model_ses = (
        SimpleExpSmoothing(train)
        .fit()
    )

    forecast = model_ses.forecast(3)

    mae, rmse, mape, acc = (
        evaluate_forecast(
            test,
            forecast
        )
    )

    results.append([
        halb,
        engine,
        model,
        vehicle,
        "SES",
        mae,
        rmse,
        mape,
        acc
    ])

except:
    pass

In [116]:
try:

    model_holt = Holt(train).fit()

    forecast = model_holt.forecast(3)

    mae, rmse, mape, acc = (
        evaluate_forecast(
            test,
            forecast
        )
    )

    results.append([
        halb,
        engine,
        model,
        vehicle,
        "Holt",
        mae,
        rmse,
        mape,
        acc
    ])

except:
    pass

In [117]:
try:

    model_hw = (
        ExponentialSmoothing(
            train,
            trend='add',
            seasonal='add',
            seasonal_periods=12
        )
        .fit()
    )

    forecast = model_hw.forecast(3)

    mae, rmse, mape, acc = (
        evaluate_forecast(
            test,
            forecast
        )
    )

    results.append([
        halb,
        engine,
        model,
        vehicle,
        "Holt Winters",
        mae,
        rmse,
        mape,
        acc
    ])

except:
    pass

In [118]:
try:

    model_arima = (
        ARIMA(
            train,
            order=(1,1,1)
        )
        .fit()
    )

    forecast = model_arima.forecast(3)

    mae, rmse, mape, acc = (
        evaluate_forecast(
            test,
            forecast
        )
    )

    results.append([
        halb,
        engine,
        model,
        vehicle,
        "ARIMA",
        mae,
        rmse,
        mape,
        acc
    ])

except:
    pass

In [119]:
try:

    model_sarima = (
        SARIMAX(
            train,
            order=(1,1,1),
            seasonal_order=(1,1,1,12)
        )
        .fit(disp=False)
    )

    forecast = model_sarima.forecast(3)

    mae, rmse, mape, acc = (
        evaluate_forecast(
            test,
            forecast
        )
    )

    results.append([
        halb,
        engine,
        model,
        vehicle,
        "SARIMA",
        mae,
        rmse,
        mape,
        acc
    ])

except:
    pass

In [120]:
results_df = pd.DataFrame(
    results,
    columns=[
        'Halb',
        'Engine',
        'Model',
        'Vehicle_Type',
        'Model_Name',
        'MAE',
        'RMSE',
        'MAPE',
        'Accuracy'
    ]
)

In [121]:
best_models = (
    results_df
    .sort_values('MAPE')
    .groupby(
        [
            'Halb',
            'Engine',
            'Model',
            'Vehicle_Type'
        ]
    )
    .first()
    .reset_index()
)

In [122]:
results_df.to_csv(
    "all_model_results.csv",
    index=False
)

best_models.to_csv(
    "best_models.csv",
    index=False
)

In [123]:
print(train)

print(test)

Month
2023-01-04    0
2023-01-05    0
2023-01-06    0
2023-01-07    0
2023-01-08    0
2023-01-09    0
2023-01-10    0
2023-01-11    0
2023-01-12    0
2024-01-01    0
2024-01-02    0
2024-01-03    0
2024-01-04    0
2024-01-05    0
2024-01-06    0
2024-01-07    0
2024-01-08    0
2024-01-09    0
2024-01-10    0
2024-01-11    0
2024-01-12    0
Name: total_demand, dtype: int64
Month
2025-01-01    0
2025-01-02    0
2025-01-03    0
Name: total_demand, dtype: int64

In [124]:
print(train.index.min())
print(train.index.max())

print(test.index.min())
print(test.index.max())

2023-01-04 00:00:00
2024-01-12 00:00:00
2025-01-01 00:00:00
2025-01-03 00:00:00

In [125]:
print(df['Month'].head(20))

0    2023-01-04
1    2023-01-05
2    2023-01-06
3    2023-01-07
4    2023-01-08
5    2023-01-09
6    2023-01-10
7    2023-01-11
8    2023-01-12
9    2024-01-01
10   2024-01-02
11   2024-01-03
12   2024-01-04
13   2024-01-05
14   2024-01-06
15   2024-01-07
16   2024-01-08
17   2024-01-09
18   2024-01-10
19   2024-01-11
Name: Month, dtype: datetime64[us]