In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("final_data_for_vehicle_forecasting.csv")

In [3]:
df.head()

,Halb,engine_type,map_model,Vehicle_Type,Month,total_demand
0,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,01/04/2023,0
1,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,01/05/2023,0
2,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,01/06/2023,0
3,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,01/07/2023,0
4,80206319,E483_BS3_DSL,10.60 P/stg with MRF tyres,Bus,01/08/2023,0

In [4]:
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

(49680, 6)

Columns:
Index(['Halb', 'engine_type', 'map_model', 'Vehicle_Type', 'Month',
       'total_demand'],
      dtype='str')

Missing Values:
Halb            0
engine_type     0
map_model       0
Vehicle_Type    0
Month           0
total_demand    0
dtype: int64

In [5]:
print(df['Month'].head(30))

0     01/04/2023
1     01/05/2023
2     01/06/2023
3     01/07/2023
4     01/08/2023
5     01/09/2023
6     01/10/2023
7     01/11/2023
8     01/12/2023
9     01/01/2024
10    01/02/2024
11    01/03/2024
12    01/04/2024
13    01/05/2024
14    01/06/2024
15    01/07/2024
16    01/08/2024
17    01/09/2024
18    01/10/2024
19    01/11/2024
20    01/12/2024
21    01/01/2025
22    01/02/2025
23    01/03/2025
24    01/04/2023
25    01/05/2023
26    01/06/2023
27    01/07/2023
28    01/08/2023
29    01/09/2023
Name: Month, dtype: str

In [6]:
df['Month'] = pd.to_datetime(
    df['Month'],
    format='%d/%m/%Y'
)

In [7]:
print(df['Month'].min())
print(df['Month'].max())

2023-04-01 00:00:00
2025-03-01 00:00:00

In [8]:
print(df['total_demand'].describe())

count    49680.000000
mean         3.211131
std         17.137720
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        677.000000
Name: total_demand, dtype: float64

In [9]:
print("Total Demand Sum:", df['total_demand'].sum())

Total Demand Sum: 159529

In [10]:
print("HALB:", df['Halb'].nunique())
print("Engine:", df['engine_type'].nunique())
print("Model:", df['map_model'].nunique())
print("Vehicle Type:", df['Vehicle_Type'].nunique())

HALB: 1772
Engine: 49
Model: 330
Vehicle Type: 3

In [11]:
sample = (
    df.groupby('Month')['total_demand']
      .sum()
      .reset_index()
)

print(sample)

        Month  total_demand
0  2023-04-01          6558
1  2023-05-01          8335
2  2023-06-01          5517
3  2023-07-01          6248
4  2023-08-01          4970
5  2023-09-01          4303
6  2023-10-01          7425
7  2023-11-01          6925
8  2023-12-01          7536
9  2024-01-01          6218
10 2024-02-01          6004
11 2024-03-01          7056
12 2024-04-01          6867
13 2024-05-01          5756
14 2024-06-01          6762
15 2024-07-01          6534
16 2024-08-01          5371
17 2024-09-01          5753
18 2024-10-01          6180
19 2024-11-01          5549
20 2024-12-01          7094
21 2025-01-01          8428
22 2025-02-01         10006
23 2025-03-01          8134

In [12]:
print(df['Month'].min())
print(df['Month'].max())

2023-04-01 00:00:00
2025-03-01 00:00:00

In [13]:
print(df['total_demand'].describe())

count    49680.000000
mean         3.211131
std         17.137720
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        677.000000
Name: total_demand, dtype: float64

In [14]:
print("Total Demand Sum:", df['total_demand'].sum())

Total Demand Sum: 159529

In [15]:
segment_summary = (
    df.groupby(
        ['Halb',
         'engine_type',
         'map_model',
         'Vehicle_Type']
    )['total_demand']
    .sum()
    .reset_index()
)

segment_summary = segment_summary.sort_values(
    'total_demand',
    ascending=False
)

print(segment_summary.head(20))

           Halb   engine_type                map_model Vehicle_Type  \
861    99106154  E494_BS6_DSL             Pro3019-Cowl           HD
1559   CL4352CW  E494_BS6_DSL                  Pro3018          LMD
1347   CL4097CW  E474_BS6_DSL           Pro 2110-P/stg          LMD
1275   CL3986CW  E494_BS6_DSL                  Pro3019           HD
862    99107163  E494_BS6_DSL             Pro3019-Cowl           HD
1344   CL4095CW  E474_BS6_DSL           Pro 2110-P/stg          LMD
584    95205612  E474_BS6_DSL  2090-new sky line-p/stg          Bus
1276   CL3988CW  E494_BS6_DSL                  Pro3019           HD
1303   CL4050CW  E474_BS6_DSL       Pro 2059XP-PREMIUM          LMD
548    95105563  E474_BS6_DSL  2075-new sky line-p/stg          Bus
1557   CL4349CW  E494_BS6_DSL                  Pro3018          LMD
1345  CL4095RUP  E474_BS6_DSL  2075-new sky line-p/stg          Bus
943    99306197  E474_BS6_DSL           Pro 2110-P/stg          LMD
946    99306366  E474_BS6_DSL           Pro 2110-P/stg          LMD
1855  CL6357RUP  E366_BS6_DSL  2065-new sky line-p/stg          Bus
1507   CL4286CW  E494_BS6_DSL        Pro 2118- Premium          LMD
1335  CL4088RUP  E474_BS6_DSL  2090-new sky line-p/stg          Bus
1324   CL4081CW  E474_BS6_DSL      Pro 2095XPT-PREMIUM          LMD
1487   CL4261CW  E494_BS6_DSL          Pro3019-PREMIUM           HD
552    95105628  E366_BS6_DSL  2065-new sky line-p/stg          Bus

      total_demand
861           5275
1559          3671
1347          3554
1275          3421
862           3028
1344          2990
584           2806
1276          2790
1303          2693
548           2510
1557          2297
1345          2174
943           1849
946           1842
1855          1821
1507          1649
1335          1601
1324          1571
1487          1389
552           1145

In [16]:
print("Total Segments:",
      len(segment_summary))

print("Segments with demand > 0:",
      (segment_summary['total_demand'] > 0).sum())

Total Segments: 2070
Segments with demand > 0: 1629

In [17]:
print(segment_summary.head(20))

           Halb   engine_type                map_model Vehicle_Type  \
861    99106154  E494_BS6_DSL             Pro3019-Cowl           HD
1559   CL4352CW  E494_BS6_DSL                  Pro3018          LMD
1347   CL4097CW  E474_BS6_DSL           Pro 2110-P/stg          LMD
1275   CL3986CW  E494_BS6_DSL                  Pro3019           HD
862    99107163  E494_BS6_DSL             Pro3019-Cowl           HD
1344   CL4095CW  E474_BS6_DSL           Pro 2110-P/stg          LMD
584    95205612  E474_BS6_DSL  2090-new sky line-p/stg          Bus
1276   CL3988CW  E494_BS6_DSL                  Pro3019           HD
1303   CL4050CW  E474_BS6_DSL       Pro 2059XP-PREMIUM          LMD
548    95105563  E474_BS6_DSL  2075-new sky line-p/stg          Bus
1557   CL4349CW  E494_BS6_DSL                  Pro3018          LMD
1345  CL4095RUP  E474_BS6_DSL  2075-new sky line-p/stg          Bus
943    99306197  E474_BS6_DSL           Pro 2110-P/stg          LMD
946    99306366  E474_BS6_DSL           Pro 2110-P/stg          LMD
1855  CL6357RUP  E366_BS6_DSL  2065-new sky line-p/stg          Bus
1507   CL4286CW  E494_BS6_DSL        Pro 2118- Premium          LMD
1335  CL4088RUP  E474_BS6_DSL  2090-new sky line-p/stg          Bus
1324   CL4081CW  E474_BS6_DSL      Pro 2095XPT-PREMIUM          LMD
1487   CL4261CW  E494_BS6_DSL          Pro3019-PREMIUM           HD
552    95105628  E366_BS6_DSL  2065-new sky line-p/stg          Bus

      total_demand
861           5275
1559          3671
1347          3554
1275          3421
862           3028
1344          2990
584           2806
1276          2790
1303          2693
548           2510
1557          2297
1345          2174
943           1849
946           1842
1855          1821
1507          1649
1335          1601
1324          1571
1487          1389
552           1145

In [18]:
print("Segments with demand > 0:",
      (segment_summary['total_demand'] > 0).sum())

Segments with demand > 0: 1629

In [19]:
overall_series = (
    df.groupby('Month')['total_demand']
      .sum()
      .sort_index()
)

print(overall_series)

Month
2023-04-01     6558
2023-05-01     8335
2023-06-01     5517
2023-07-01     6248
2023-08-01     4970
2023-09-01     4303
2023-10-01     7425
2023-11-01     6925
2023-12-01     7536
2024-01-01     6218
2024-02-01     6004
2024-03-01     7056
2024-04-01     6867
2024-05-01     5756
2024-06-01     6762
2024-07-01     6534
2024-08-01     5371
2024-09-01     5753
2024-10-01     6180
2024-11-01     5549
2024-12-01     7094
2025-01-01     8428
2025-02-01    10006
2025-03-01     8134
Name: total_demand, dtype: int64

In [20]:
train = overall_series.loc[:'2024-12-01']

test = overall_series.loc['2025-01-01':'2025-03-01']

In [21]:
print(train.shape)
print(test.shape)

print(test)

(21,)
(3,)
Month
2025-01-01     8428
2025-02-01    10006
2025-03-01     8134
Name: total_demand, dtype: int64

In [22]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    mean_absolute_percentage_error
)

import numpy as np

def evaluate(actual, forecast):

    mae = mean_absolute_error(
        actual,
        forecast
    )

    rmse = np.sqrt(
        mean_squared_error(
            actual,
            forecast
        )
    )

    mape = (
        mean_absolute_percentage_error(
            actual,
            forecast
        ) * 100
    )

    accuracy = 100 - mape

    return mae, rmse, mape, accuracy

In [23]:
moving_avg = train.tail(3).mean()

forecast = [moving_avg] * 3

In [24]:
print("Actual")
print(test.values)

print()

print("Forecast")
print(forecast)

Actual
[ 8428 10006  8134]

Forecast
[np.float64(6274.333333333333), np.float64(6274.333333333333), np.float64(6274.333333333333)]

In [25]:
mae, rmse, mape, acc = evaluate(
    test,
    forecast
)

print("MAE:", mae)
print("RMSE:", rmse)
print("MAPE:", mape)
print("Accuracy:", acc)

MAE: 2581.666666666667
RMSE: 2709.365013758349
MAPE: 28.570293346814097
Accuracy: 71.4297066531859

In [26]:
results = []

In [27]:
moving_avg = train.tail(3).mean()

forecast_ma = [moving_avg] * 3

mae, rmse, mape, acc = evaluate(
    test,
    forecast_ma
)

results.append([
    'Moving Average',
    mae,
    rmse,
    mape,
    acc
])

In [28]:
from statsmodels.tsa.holtwinters import SimpleExpSmoothing

ses_model = SimpleExpSmoothing(
    train
).fit()

forecast_ses = ses_model.forecast(3)

mae, rmse, mape, acc = evaluate(
    test,
    forecast_ses
)

results.append([
    'SES',
    mae,
    rmse,
    mape,
    acc
])

/Users/utkarshraj/Desktop/Internship/Vehicle Demand Forecasting/.venv/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)

In [29]:
from statsmodels.tsa.holtwinters import Holt

holt_model = Holt(
    train
).fit()

forecast_holt = holt_model.forecast(3)

mae, rmse, mape, acc = evaluate(
    test,
    forecast_holt
)

results.append([
    'Holt',
    mae,
    rmse,
    mape,
    acc
])

/Users/utkarshraj/Desktop/Internship/Vehicle Demand Forecasting/.venv/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)

In [30]:
from statsmodels.tsa.arima.model import ARIMA

arima_model = ARIMA(
    train,
    order=(1,1,1)
).fit()

forecast_arima = arima_model.forecast(
    steps=3
)

mae, rmse, mape, acc = evaluate(
    test,
    forecast_arima
)

results.append([
    'ARIMA',
    mae,
    rmse,
    mape,
    acc
])

/Users/utkarshraj/Desktop/Internship/Vehicle Demand Forecasting/.venv/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)
/Users/utkarshraj/Desktop/Internship/Vehicle Demand Forecasting/.venv/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)
/Users/utkarshraj/Desktop/Internship/Vehicle Demand Forecasting/.venv/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)

In [31]:
from statsmodels.tsa.statespace.sarimax import SARIMAX

sarima_model = SARIMAX(
    train,
    order=(1,1,1),
    seasonal_order=(1,1,1,12)
).fit(disp=False)

forecast_sarima = sarima_model.forecast(
    steps=3
)

mae, rmse, mape, acc = evaluate(
    test,
    forecast_sarima
)

results.append([
    'SARIMA',
    mae,
    rmse,
    mape,
    acc
])

/Users/utkarshraj/Desktop/Internship/Vehicle Demand Forecasting/.venv/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)
/Users/utkarshraj/Desktop/Internship/Vehicle Demand Forecasting/.venv/lib/python3.12/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)
/Users/utkarshraj/Desktop/Internship/Vehicle Demand Forecasting/.venv/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [32]:
results_df = pd.DataFrame(
    results,
    columns=[
        'Model',
        'MAE',
        'RMSE',
        'MAPE',
        'Accuracy'
    ]
)

results_df.sort_values(
    'MAPE'
)

            Model          MAE         RMSE       MAPE   Accuracy
2            Holt  1563.079595  1796.224341  16.934133  83.065867
4          SARIMA  1850.524113  2023.307373  20.250527  79.749473
1             SES  2341.571143  2481.654976  25.836943  74.163057
0  Moving Average  2581.666667  2709.365014  28.570293  71.429707
3           ARIMA  2594.639944  2728.585297  28.703163  71.296837

In [33]:
ml_df = overall_series.reset_index()

ml_df.columns = ['Month', 'Demand']

ml_df.head()

       Month  Demand
0 2023-04-01    6558
1 2023-05-01    8335
2 2023-06-01    5517
3 2023-07-01    6248
4 2023-08-01    4970

In [34]:
ml_df['Year'] = ml_df['Month'].dt.year

ml_df['Month_Num'] = ml_df['Month'].dt.month

ml_df['Quarter'] = ml_df['Month'].dt.quarter

In [35]:
ml_df['lag_1'] = ml_df['Demand'].shift(1)

ml_df['lag_2'] = ml_df['Demand'].shift(2)

ml_df['lag_3'] = ml_df['Demand'].shift(3)

In [36]:
ml_df['rolling_mean_3'] = (
    ml_df['Demand']
    .rolling(3)
    .mean()
)

In [37]:
ml_df = ml_df.dropna()

ml_df.head()

,Month,Demand,Year,Month_Num,Quarter,lag_1,lag_2,lag_3,rolling_mean_3
3,2023-07-01,6248,2023,7,3,5517.0,8335.0,6558.0,6700.000000
4,2023-08-01,4970,2023,8,3,6248.0,5517.0,8335.0,5578.333333
5,2023-09-01,4303,2023,9,3,4970.0,6248.0,5517.0,5173.666667
6,2023-10-01,7425,2023,10,4,4303.0,4970.0,6248.0,5566.000000
7,2023-11-01,6925,2023,11,4,7425.0,4303.0,4970.0,6217.666667

In [38]:
print(ml_df.shape)

ml_df.head()

(21, 9)

,Month,Demand,Year,Month_Num,Quarter,lag_1,lag_2,lag_3,rolling_mean_3
3,2023-07-01,6248,2023,7,3,5517.0,8335.0,6558.0,6700.000000
4,2023-08-01,4970,2023,8,3,6248.0,5517.0,8335.0,5578.333333
5,2023-09-01,4303,2023,9,3,4970.0,6248.0,5517.0,5173.666667
6,2023-10-01,7425,2023,10,4,4303.0,4970.0,6248.0,5566.000000
7,2023-11-01,6925,2023,11,4,7425.0,4303.0,4970.0,6217.666667

In [39]:
train_ml = ml_df[
    ml_df['Month'] <= '2024-12-01'
]

test_ml = ml_df[
    ml_df['Month'] >= '2025-01-01'
]

In [40]:
features = [
    'Year',
    'Month_Num',
    'Quarter',
    'lag_1',
    'lag_2',
    'lag_3',
    'rolling_mean_3'
]

X_train = train_ml[features]

y_train = train_ml['Demand']

X_test = test_ml[features]

y_test = test_ml['Demand']

In [41]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()

lr_model.fit(
    X_train,
    y_train
)

forecast_lr = lr_model.predict(
    X_test
)

mae, rmse, mape, acc = evaluate(
    y_test,
    forecast_lr
)

results.append([
    'Linear Regression',
    mae,
    rmse,
    mape,
    acc
])

In [42]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf_model.fit(
    X_train,
    y_train
)

forecast_rf = rf_model.predict(
    X_test
)

mae, rmse, mape, acc = evaluate(
    y_test,
    forecast_rf
)

results.append([
    'Random Forest',
    mae,
    rmse,
    mape,
    acc
])

In [43]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

xgb_model.fit(
    X_train,
    y_train
)

forecast_xgb = xgb_model.predict(
    X_test
)

mae, rmse, mape, acc = evaluate(
    y_test,
    forecast_xgb
)

results.append([
    'XGBoost',
    mae,
    rmse,
    mape,
    acc
])

In [44]:
results_df = pd.DataFrame(
    results,
    columns=[
        'Model',
        'MAE',
        'RMSE',
        'MAPE',
        'Accuracy'
    ]
)

results_df = results_df.sort_values(
    'MAPE'
)

results_df

               Model           MAE          RMSE          MAPE    Accuracy
5  Linear Regression  3.941144e-12  3.964395e-12  4.514345e-14  100.000000
2               Holt  1.563080e+03  1.796224e+03  1.693413e+01   83.065867
4             SARIMA  1.850524e+03  2.023307e+03  2.025053e+01   79.749473
1                SES  2.341571e+03  2.481655e+03  2.583694e+01   74.163057
6      Random Forest  2.493050e+03  2.661380e+03  2.746867e+01   72.531331
7            XGBoost  2.513484e+03  2.703772e+03  2.765076e+01   72.349235
0     Moving Average  2.581667e+03  2.709365e+03  2.857029e+01   71.429707
3              ARIMA  2.594640e+03  2.728585e+03  2.870316e+01   71.296837

In [79]:
df.to_excel("forecast_resultsss.xlsx", index=False)